name: Testing CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # pull_request:
  #   branches: ["main"]

jobs: 
  greet: 
    runs-on : ubuntu-latest
    steps:
    - name: Shoutout
      run: echo "Hello everyone"