name: Testing CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # pull_request:
  #   branches: ["main"]

jobs: 
  greet: 
    runs-on : ubuntu-latest
    steps:
    - name: Shoutout
      run: echo "Hello everyone"

    - name: clone project
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v3

    - name: install dependencies
      run: pip install -r requirements.txt