name: Testing CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # pull_request:
  #   branches: ["main"]

jobs: 
  test: 
    runs-on : ubuntu-latest
    steps:
    - name: Shoutout
      run: echo "Hello everyone"

    - name: clone project
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v3

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: run test
      run : echo "Test completed"
  deploy: 
    runs-on : ubuntu-latest
    needs: test

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/django:latest
